currency: false
balancing: nation
balancingpercent: 10;
reloadhours: 6
inviteaging: 28
blockpearls: true
datasource:
    use_mysql: true
    mysql:
        db_name: nationsatwar
        user: 
        pass: 
        url: localhost
        port: 3306