name: Nations
main: org.nationsatwar.nations.Nations
version: 0.1
[depends]: PermissionsBukkit

commands:
  found:
    description: Creates a nation.
    usage: /found
    permission: nationsatwar.nations.player
  world:
    description: Shows information about the world.
    usage: /world
    permission: nationsatwar.nations.player
  invite:
    description: Creates invitations.
    usage: /invite [player]
    permission: nationsatwar.nations.player
  accept:
    description: Accepts invitations.
    usage: /invite [player]
    permission: nationsatwar.nations.player
  claim:
    description: Claims land for your nation.
    usage: /invite [player]
    permission: nationsatwar.nations.player

permissions:
    nationsatwar.nations.player:
        description: Flags the user as an accepted nations player.
        default: true