name: Nations
main: org.nationsatwar.nations.Nations
version: 0.1
[depends]: PermissionsBukkit

commands:
  found:
    description: Creates a nation.
    usage: /found
    permission: nations.nations.user
  world:
    description: Shows information about the world.
    usage: /world
    permission: nations.nations.user
  invite:
    description: Invites a player into the nation.
    usage: /invite [player]
    permission: nations.nations.user

permissions:
    nations.nations.user:
        description: Flags the user as an accepted nations player.
        default: true