name: Nations
main: org.nationsatwar.nations.Nations
version: 0.1
[depends]: PermissionsBukkit

commands:
  found:
    description: Creates a nation.
    usage: /found
    permission: nations.nations.user
  world:
    description: Shows information about the world.
    usage: /world
    permission: nations.nations.user
  invite:
    description: Creates invitations.
    usage: /invite [player]
    permission: nations.nations.user
  accept:
    description: Accepts invitations.
    usage: /invite [player]
    permission: nations.nations.user
  claim:
    description: Claims land for your nation.
    usage: /invite [player]
    permission: nations.nations.user

permissions:
    nations.nations.user:
        description: Flags the user as an accepted nations player.
        default: true